Задачник
js-tasks-ru/js-20221021_maxim-b pull request #2
Opened 2022-10-26 17:08 UTC by MaximBurcev

2022-10-26 17:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-10-26 17:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-10-26 17:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-10-26 18:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-10-27 12:59 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  arrCopy.sort(function (a, b) {
- следует устранить дубликаты кода
- в `localeCompare` передать локали языков для сортировки
- от `toLowerCase` следует отказаться

2022-10-27 13:00 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let object = {};
проверьте `object` это `let` или `const`?

2022-10-27 13:00 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +      if (elem[0] === str) {
обратите внимание на метод массивов `includes` и исправьте решение

2022-10-27 13:01 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let object = {};
`const`

2022-10-27 13:01 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (let elem of Object.entries(obj)) {
`const`

2022-10-27 13:01 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-10-27 16:15 UTC, MaximBurcev commented on 02-javascript-data-types/3-omit/index.js
> +  for (let elem of Object.entries(obj)) {
Исправил

2022-10-27 16:16 UTC, MaximBurcev commented on 02-javascript-data-types/3-omit/index.js
> +  let object = {};
Исправил

2022-10-27 16:16 UTC, MaximBurcev commented on 02-javascript-data-types/2-pick/index.js
> +      if (elem[0] === str) {
Переделал

2022-10-27 16:16 UTC, MaximBurcev commented on 02-javascript-data-types/2-pick/index.js
> +  let object = {};
Поправил

2022-10-27 16:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-10-27 16:16 UTC, MaximBurcev commented on 02-javascript-data-types/1-sort-strings/index.js
> +  arrCopy.sort(function (a, b) {
Локали для сортировки передал. От toLowerCase отказался. Дубликаты кода устранил.

2022-10-27 16:25 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-10-28 16:38 UTC, dosandk approved these changes
👍 good

2022-10-28 16:39 UTC, merged