NotificationMessage компонент
js-tasks-ru/js-20221021_maxim-b pull request #5
Opened 2022-11-05 14:37 UTC by MaximBurcev

2022-11-05 14:38 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-05 19:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-06 18:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-07 14:24 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static counter = 0;
👍 good  лайк за статическое св-во

2022-11-07 14:24 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (div) {
может задать для `div` значение по умолчанию?
как это повлияет на код?

2022-11-07 14:25 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (NotificationMessage.counter > 0) {
тут логика неверная! предыдущий нотификейшен следует удалить, если он был показан

2022-11-07 14:25 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  getSubElements() {
👍 good

2022-11-07 14:25 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          <img class="sortable-table-image" alt="Image" src="http://magazilla.ru/jpg_zoom1/430982.jpg"></div>
а почему картинка захардкоджена?

2022-11-07 14:26 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        <span>Quantity</span>
почему `Quantity`, `Price`, захардкоджены?

2022-11-07 14:26 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        <span>Quantity</span>
следует добавить динамически

2022-11-07 14:26 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-11-07 16:04 UTC, MaximBurcev commented on 05-dom-document-loading/1-notification/index.js
> +    if (div) {
поправил

2022-11-07 16:05 UTC, MaximBurcev commented on 05-dom-document-loading/1-notification/index.js
> +    if (NotificationMessage.counter > 0) {
Передал логику

2022-11-07 16:05 UTC, MaximBurcev commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          <img class="sortable-table-image" alt="Image" src="http://magazilla.ru/jpg_zoom1/430982.jpg"></div>
Исправил

2022-11-07 16:05 UTC, MaximBurcev commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        <span>Quantity</span>
Добавил динамически

2022-11-07 16:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-07 16:05 UTC, MaximBurcev commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        <span>Quantity</span>
А почему тесты не проходят?(

2022-11-08 10:11 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-08 12:28 UTC, MaximBurcev commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        <span>Quantity</span>
Тесты прошли

2022-11-08 13:54 UTC, dosandk approved these changes
👍 good

2022-11-08 13:55 UTC, merged